/*
* 所有功能的通用常量
 */
export default class CommonConstants {

  //    账号的输入长度
  static readonly INPUT_ACCOUNT_LENGTH = 11
  //    密码的输入长度
  static readonly INPUT_PASSWORD_LENGTH = 8
  //    输入框的左填充
  static readonly INPUT_PADDING_LEFT = 10
  //    模拟登录的延迟时间
  static readonly LOGIN_DELAY_TIME = 2000
  //    组件的通用间距
  static readonly COMMON_SPACE = 12

  // 首页的标题文本
  static readonly HOME_TITLE = '首页'
  // 设置页面的标题文本
  static readonly MINE_TITLE = '我的'

  // 输入框宽度
  static readonly Full_PARENT = '100%'
  // 按钮宽度
  static readonly BUTTON_WIDTH  = '80%'
  // 登录方式间距
  static readonly LOGIN_METHODS_SPACE = '50'

  // 设置列表高度
  static readonly SET_LIST_HEIGHT = '50%'
  // 设置列表宽度
  static readonly SET_LIST_WIDTH = '42%'

  // 首页标签索引
  static readonly HOME_TAB_INDEX = 0
  // 我的设置页标签索引
  static readonly MY_TAB_INDEX = 1
}


